### ISSUE TITLE
WIP - Jenn's Doc

### ISSUE THREAD

**Issue by allthedoll** [allthedoll/TCCamp#1]
This is Jenn's main doc that she is writing, because she is _soo_ good at it. @jleaver

**Comment by allthedoll** [comment]
:shipit:

**Comment by bonniekim** [comment]
I have taken notes for this workshop. Is there a way for me to upload my photos of notes off my phone?

**Comment by jleaver** [comment]
Hi @bonniekim! That would be great! If you'd like, you can create a new issue within this repository for your notes. 

I'm not sure if there's an easy way to upload images from your phone to a GitHub issue (I'll ask around!), but in the meantime, if you put them on your desktop, you can easily [drag and drop attachments](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/).

**Comment by jleaver** [comment]
@bonniekim - If you're feeling really ambitious, you could also create a pull request in this repo (a la @sarahmaddox's PR [here](https://github.com/allthedoll/TCCamp/pull/3). :sparkles:

If that's something you'd like to try but aren't sure how, let me know and I can direct you to some resources or walk you through it!

**Comment by allthedoll** [comment]
Closing this issue; nothing's been added in 2+ weeks. :)
